[tool.poetry]
name = "spauditify"
version = "0.1.0"
description = ""
authors = ["Dom Batten <dominic.batten@googlemail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
